[package]
name = "harvestsend-contract"
version = "0.1.0"
edition = "2021"
description = "Cross-border remittance that turns into verifiable farm income history"


[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "22.0.0", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }
